# Generated by Django 3.2.6 on 2021-12-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0002_profilemodel_eo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
